# Generated by Django 3.2.11 on 2022-01-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myia', '0002_auto_20220115_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
    ]
