# Generated by Django 3.2.11 on 2022-01-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myia', '0003_alter_person_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='code',
        ),
    ]
