# Generated by Django 3.2.11 on 2022-01-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myia', '0005_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
    ]
