# Generated by Django 3.2.11 on 2022-01-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myia', '0006_alter_person_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=15, verbose_name='CPF'),
        ),
    ]
